builds:
  - main: ./starport/cmd/starport
    ldflags:
      - -s -w -X github.com/bjaanes/starport-playground/starport/internal/version.Version={{.Tag}} -X github.com/bjaanes/starport-playground/starport/internal/version.Date={{.Date}} -X github.com/bjaanes/starport-playground/starport/internal/version.Head={{.FullCommit}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
changelog:
  skip: true
release:
  prerelease: true
