#!/bin/bash

# generates static Go files to embed node cli programs into Starport for linux and darwin.

set -e

cd ./scripts/data/gen-nodetime

npm ci # Faster in ci + stops package-lock changes (this should happen in commits anyway)
npm run build

tar -czvf nodetime-linux-amd64.tar.gz nodetime-linux-x64
tar -czvf nodetime-linux-arm64.tar.gz nodetime-linux-arm64
tar -czvf nodetime-darwin-amd64.tar.gz nodetime-macos-x64
tar -czvf nodetime-darwin-arm64.tar.gz nodetime-macos-arm64

mv nodetime-*.tar.gz ../../../starport/pkg/nodetime/data

rm nodetime-linux-x64 nodetime-linux-arm64 nodetime-macos-x64 nodetime-macos-arm64
rm -rf dist/
